//! The four prompts of the compiler pipeline, transcribed from the reference.
//!
//! They live in their own file for one reason: they are data, and the only way to know a
//! transcription is exact is to compare it against the payload the reference sent. The compiler
//! golden does that — it records the policy from the reference's own transport, and the port's
//! payload is compared to it byte for byte. A sentence that lost a space at a line join fails
//! the build rather than quietly asking the model something slightly else.
//!
//! Generated from `tests/golden/ai-compile-golden.json`; see `scripts/generate_compile_golden.py`.

/// The compiler, the ambiguity judge, the duplicate detector and the probability estimate.
pub const COMPILER_POLICY: &str = r"Compile an objective, publicly verifiable future YES/NO/INVALID question. Translate the original input into English faithfully, preserving all entities, amounts, criteria, deadlines and timezones; never add or remove conditions. The English specification will be shown to the user for review before publication. Preserve user intent, explicitly resolve timezone to UTC, and use exactly now_ms as open_at_ms. Output close_at_utc as exact YYYY-MM-DDTHH:MM:SSZ; NEVER calculate or output close_at_ms. Repeat close_at_utc verbatim in canonical_question and each YES/NO rule condition, so human text and deadlines cannot diverge. Avoid alternative numeric dates in those texts. share_title must be a concise English question of at most 60 characters and must be timeless: omit ALL deadlines, dates, end-of-year, before/by date, this/next year and other timeframe phrases. The UI displays the exact closing time separately. Preserve product names/model numbers and the substantive event; never substitute an approximate or different deadline in the title. Do not invent a missing deadline or definition: encode high ambiguity so validation rejects it. Prefer one specific official text source that can resolve the question; add sources only when criteria require them. Optional fallback sources are used only when no primary can be retrieved, not mandatory corroboration. Choose 1-4 directly accessible relevant text sources on the approved hosts; all primary sources must be official. No login pages, search redirects, generic company homepage without resolution evidence, PDFs or private personal information. Document exhaustive YES/NO/INVALID clauses and source failure rules. Identify every supplied semantically similar candidate by candidate_ref (c0, c1, etc.) only; NEVER output or copy forecast_id or specification_hash in duplicate_candidates. References select the exact supplied identity and specification; assess similarity and material rule differences. Never invent or repeat a reference. Integer ambiguity score 0..10000.";

/// Appended to the compiler policy when the input declares a measurement interval.
pub const WINDOW_POLICY: &str = r" This input specifies one measurement window. Its start and end have different roles: copy measurement_window.canonical_expression exactly once into canonical_question and each YES/NO rule condition, including the opening [ and closing ). Set close_at_utc to its end_at_utc. Never replace start by end, move the window, omit it or use start as a separate deadline. Outside that bracket interval, every explicit time must be the exact closing UTC timestamp; the earlier instruction to avoid alternative dates does not remove this verified window start.";

pub const AMBIGUITY_POLICY: &str = r"Independently judge exact criteria for objective coverage, non-overlap, timeframe, missing definitions and whether fetched source documents and dates preserve the original user's question without changing intent. Verify every public specification field is English, including the title, all rules, invalidation rules and source names; set english_language_passed accordingly. Compare against the exact original-language input and set intent_preserved=false if translation adds or removes a criterion, amount, entity, deadline or timezone. Verify the share title is a faithful timeless description of the same event/product without a deadline or timeframe phrase; set title_consistent=false if it changes the entity, product, amount, event or temporal meaning. Omitting the deadline from the title is intentional because the exact closing time is displayed separately, while the canonical question and rules retain it. Verify documents are genuine and appropriate for eventual resolution. Reject if unavailable sources are required by any outcome clause; a source subset must satisfy the published criteria, never waive a required document. unverifiable or ambiguous questions. Do not rewrite the specification. Ambiguity limit is 1000 basis points. Mere source page reachability is insufficient.";

pub const DUPLICATE_POLICY: &str = r"Independently compare every supplied candidate. Verify specification.duplicate_candidates includes every semantically similar candidate, IDs/hashes and material rule differences. Report candidates_accurate=false if any match is omitted or misclassified. Threshold 8500 basis points. An empty candidate search is complete, never invent matching forecasts.";

pub const FORECAST_POLICY: &str = r"Estimate the probability of the published YES clause ultimately being satisfied, given only the supplied source context and knowledge you actually have as of as_of_utc (the current evaluation date, not your training cutoff). Distinguish facts supported by the retained source documents from prior or historical knowledge. Do not assert a product is currently the latest version, a company currently does something, or any other current fact unless the retained source documents support it. If source context lacks current information, explicitly acknowledge that uncertainty instead of presenting stale model knowledge as current. This is a fallible forecast, not a resolution or evidence of the future. Use integer yesProbabilityBp 0..10000 and a concise rationale acknowledging important uncertainty. Never invent web research, crowd forecasts or observations. No betting, payouts or investment advice.";
